apiVersion: v1
kind: Service
metadata:
  name: reactjs-app-service
  namespace: default
  labels:
    app: reactjs-app
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: reactjs-app
  ports:
    - protocol: TCP
      port: 85
      targetPort: 3000
  type: LoadBalancer
  sessionAffinity: None # Use "ClientIP" if session affinity is needed